DROP SEQUENCE SEQ_VIDEO_ID;
DROP SEQUENCE SEQ_SINGER_ID;
DROP TABLE VIDEO;
DROP TABLE SINGER;

CREATE TABLE SINGER
(
	SINGER_ID	NUMBER PRIMARY KEY,
	NAME		VARCHAR2(100),
	COUNTRY		VARCHAR2(50),
	LANG		CHAR(3),
	IMAGE_URI	VARCHAR2(250)
);
CREATE SEQUENCE SEQ_SINGER_ID START WITH 1000 INCREMENT BY 1;


CREATE TABLE VIDEO
(
   VIDEO_ID		NUMBER PRIMARY KEY,
   LANG			CHAR(3),
   TYPE			VARCHAR2(20),
   YOUTUBE_LINK	VARCHAR2(255),
   NAME			VARCHAR2(255),
   PERFORMED_BY	VARCHAR2(255),
   FEATURE_BY	VARCHAR2(255)
);

CREATE TABLE VIDEO_FILTER
(
  VIDEO_FILTER_ID  INTEGER PRIMARY KEY,
  TITLE VARCHAR2(255),
  ICON VARCHAR2(255),
  BY_COLUMN VARCHAR2(255)
);

CREATE SEQUENCE SEQ_VIDEO_ID START WITH 1000 INCREMENT BY 1;

INSERT INTO VIDEO_FILTER(VIDEO_FILTER_ID, TITLE, ICON, BY_COLUMN) VALUES (1, 'Language', 'language', 'LANG');
INSERT INTO VIDEO_FILTER(VIDEO_FILTER_ID, TITLE, ICON, BY_COLUMN) VALUES (2, 'Singer', 'person', 'PERFORMED_BY');


