server:
  port: 8088

spring:
  datasource:
    jdbcUrl:  jdbc:oracle:thin:@localhost:1521:orcl2
    username: scott
    password: toronto08
    driverClassName: oracle.jdbc.driver.OracleDriver